public class WXYZConversion
{
    public static void main(String[] args)
    {
        final String input = "JNPGCZBUXHJAVWXGWIZAXTIQYMRRSSYDNUWCJYVZVZZCYZYKWUMOJNZYUJIKCWXUVDDNOYJDXYIXADXJYZNZTSNQDXGUBYSZPRCRPQYIPTXCSIHNZXWFWSQKVYOHWIZJYWZDQSLPIFXRYWYLXWWYDCBWIKJQGWSUXPHCORZXSXLWWOIZPIMQXCWVCMAYWKKPRNWAYYATXCHQCZKTIWIRLOZVQWKXZGYRZUQJXDJQQYMYLNBZXWWMJXPZXKYPGWRETBPPDHUMQMKNUYHFGQKHMYKJKWYTIBZSTOZFHLQVYXLGCNIEXQFAGBWAFMXSWXTCWZKXSAXUZFLUYPWIGKWYUDTOOYYWZYQZXDVJSYSTGJWXNZGZOZSZCXCHZERWCIWYTIPQRWXZWCYYQYUWTNGZXZUBYKYVZWPEKOYZNWKYGPOYXLTWYYTAFYXPXXQWCWSZLMXRGKVCCWLANWWCBZYWLIRYGJRHMKWVBWXWGRLETQNZHYAQUTZK";

        // The input string after applying the transformations manually
        final String manualSolution = "JNPGCZBUEHJAVEGIZAETIQYMRRSSYDNUCJYVZVZZCEYKUMOJNZYUJIKCEUVDDNOYJDXYIXADEJENZTSNQDEGUBYSZPRCRPQYIPTECSIHNZEFSQKVYOHIZJEDQSLPIFERYYLEYDCBIKJQGSUEPHCORZESELOIZPIMQECVCMAYKKPRNAYYATECHQCZKTIIRLOZVQKEZGYRZUQJEDJQQYMYLNBZXMJXPZEKYPGRETBPPDHUMQMKNUYHFGQKHMYKJKYTIBZSTOZFHLQVYELGCNIEEQFAGBAFMESETCZKXSAEUZFLUYPIGKYUDTOOYEYQZEDVJSYSTGJENZGZOZSZCECHZERCIYTIPQREZCYYQYUTNGZEZUBYKYVZPEKOENKYGPOYELTYYTAFYXPEEQCSZLMERGKVCCLANCBZYLIRYGJRHMKVBEGRLETQNZHYAQUTZK";

        String firstTransformation = input.replaceAll("W","");
        String secondTransformation = firstTransformation.replaceAll("(X)(?=..[^X])", "E");
        String thirdTransformation = secondTransformation.replaceAll("YZ", "E");

        System.out.println(manualSolution.equals(thirdTransformation)); // Debug use: this should return true.

        System.out.println("Five characters starting at (including) the 432nd character: " + thirdTransformation.substring(431, 436));
    }
}